project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Home h
    right:
      - href : talks.qmd
        text: My PhD
      - href: blog/index.qmd
      - href: projects/index.qmd
    tools:
      - icon : github
        href : https://github.com/chamathe
        

format:
  html:
    fontsize: 20px
    theme: [cosmo, styles.scss]

