project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Home
    right:
      - href : talks.qmd
        text: My PhD
      - href: blog/index.qmd
      - href: projects/index.qmd
    tools:
      - icon : bi bi-envelope-at-fill
        href : mailto:chamath.ekanayake@napier.ac.uk
      - icon : github
        href : https://github.com/chamathe
      - icon : linkedin
        href : https://www.linkedin.com/in/chamath-ekanayake/
      - icon : bi bi-mortarboard-fill
        href : https://scholar.google.com/citations?user=WGyRK1UAAAAJ&hl=en
        

format:
  html:
    fontsize: 20px
    theme: [cosmo, styles.scss]

